title: "Inaya Rizvi"
description: "Aspiring Data Scientist | Python, R, SQL, Data Visualization"
show_downloads: trueremote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-themetheme: jekyll-theme-dinky
baseurl: ""
url: "https://inaya-r.github.io"
