title: "Inaya Rizvi"
description: "Aspiring Data Scientist | Python, R, SQL, Data Visualization"
show_downloads: true
remote_theme: mmistakes/minimal-mistakes
baseurl: ""
url: "https://inaya-r.github.io"
